### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Kei0Engineer** [spmonkey/GHR#2]
GHR-main\lib\logo.py:21: SyntaxWarning: invalid escape sequence '\_'
  logo = """

  ________       .__       .___                      .__                                    .___ __________           .___
 /  _____/  ____ |  |    __| _/____   ____           |  |__   ____   ____ ______   ____   __| _/ \______   \ ____   __| _/
/   \  ___ /  _ \|  |   / __ |/ __ \ /    \   ______ |  |  \ /  _ \ /  _ \\____ \_/ __ \ / __ |   |       _//  _ \ / __ |
\    \_\  (  <_> )  |__/ /_/ \  ___/|   |  \ /_____/ |   Y  (  <_> |  <_> )  |_> >  ___// /_/ |   |    |   (  <_> ) /_/ |
 \______  /\____/|____/\____ |\___  >___|  /         |___|  /\____/ \____/|   __/ \___  >____ |   |____|_  /\____/\____ |
        \/                  \/    \/     \/               \/              |__|        \/     \/          \/            \/

花果山出品

 [*] 正在检测模块库安装及更新，请稍后......
 [+] 模块库安装及更新已完成，请放心使用！

[32mhttp://testphp.vulnweb.com/ --> 200[0m
Exception ignored in: <finalize object at 0x22e43e7f220; dead>
Traceback (most recent call last):
  File "C:\python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\urllib3\connectionpool.py", line 1182, in _close_pool_connections
    conn = pool.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\queue.py", line 182, in get
    self.not_full.notify()
  File "C:\python\Lib\threading.py", line 404, in notify
    if not self._is_owned():
           ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\threading.py", line 317, in _is_owned
    if self._lock.acquire(False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\gevent\thread.py", line 132, in acquire
    sleep()
  File "C:\python\Lib\site-packages\gevent\hub.py", line 159, in sleep
    waiter.get()
  File "src\\gevent\\_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
Exception ignored in: <finalize object at 0x22e44a80640; dead>
Traceback (most recent call last):
  File "C:\python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\urllib3\connectionpool.py", line 1182, in _close_pool_connections
    conn = pool.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\queue.py", line 182, in get
    self.not_full.notify()
  File "C:\python\Lib\threading.py", line 404, in notify
    if not self._is_owned():
           ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\threading.py", line 317, in _is_owned
    if self._lock.acquire(False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\gevent\thread.py", line 132, in acquire
    sleep()
  File "C:\python\Lib\site-packages\gevent\hub.py", line 159, in sleep
    waiter.get()
  File "src\\gevent\\_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
Exception ignored in: <finalize object at 0x22e44a82300; dead>
Traceback (most recent call last):
  File "C:\python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\urllib3\connectionpool.py", line 1182, in _close_pool_connections
    conn = pool.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\queue.py", line 182, in get
    self.not_full.notify()
  File "C:\python\Lib\threading.py", line 404, in notify
    if not self._is_owned():
           ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\threading.py", line 317, in _is_owned
    if self._lock.acquire(False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\gevent\thread.py", line 132, in acquire
    sleep()
  File "C:\python\Lib\site-packages\gevent\hub.py", line 159, in sleep
    waiter.get()
  File "src\\gevent\\_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
Exception ignored in: <finalize object at 0x22e447e4540; dead>
Traceback (most recent call last):
  File "C:\python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\urllib3\connectionpool.py", line 1182, in _close_pool_connections
    conn = pool.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\queue.py", line 182, in get
    self.not_full.notify()
  File "C:\python\Lib\threading.py", line 404, in notify
    if not self._is_owned():
           ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\threading.py", line 317, in _is_owned
    if self._lock.acquire(False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\gevent\thread.py", line 132, in acquire
    sleep()
  File "C:\python\Lib\site-packages\gevent\hub.py", line 159, in sleep
    waiter.get()
  File "src\\gevent\\_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out
Exception ignored in: <finalize object at 0x22e448f6420; dead>
Traceback (most recent call last):
  File "C:\python\Lib\weakref.py", line 590, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\urllib3\connectionpool.py", line 1182, in _close_pool_connections
    conn = pool.get(block=False)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\queue.py", line 182, in get
    self.not_full.notify()
  File "C:\python\Lib\threading.py", line 404, in notify
    if not self._is_owned():
           ^^^^^^^^^^^^^^^^
  File "C:\python\Lib\threading.py", line 317, in _is_owned
    if self._lock.acquire(False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python\Lib\site-packages\gevent\thread.py", line 132, in acquire
    sleep()
  File "C:\python\Lib\site-packages\gevent\hub.py", line 159, in sleep
    waiter.get()
  File "src\\gevent\\_waiter.py", line 143, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: timed out

**Comment by spmonkey** [comment]
这报错与代码无关，如果不知道 TimeoutError: timed out 是什么意思，您可以去翻译一下。
如有其他bug，欢迎提交，也可以到微信群进行反馈！

**Comment by Charles7c** [comment]
> 这报错与代码无关，如果不知道 TimeoutError: timed out 是什么意思，您可以去翻译一下。 如有其他bug，欢迎提交，也可以到微信群进行反馈！

群二维码过期了

**Comment by spmonkey** [comment]
> > 这报错与代码无关，如果不知道 TimeoutError: timed out 是什么意思，您可以去翻译一下。 如有其他bug，欢迎提交，也可以到微信群进行反馈！
> 
> 群二维码过期了

群二维码已更新！
